### ISSUE TITLE
rfc0011「Command-line flag for slurping」の翻訳をする

### ISSUE THREAD

**Issue by kfly8** [jpa-perl/wg-perl-document#12]
https://github.com/Perl/RFCs/blob/master/rfcs/rfc0011.md

**Comment by bayashi** [comment]
https://github.com/perldoc-jp/module-pod-jp/pull/12

**Comment by kfly8** [comment]
👍👍👍

**Comment by kfly8** [comment]
https://github.com/perldoc-jp/module-pod-jp/pull/12 はマージしたのでクローズします！
