### ISSUE TITLE
対訳表を作成する

### ISSUE THREAD

**Issue by kfly8** [jpa-perl/wg-perl-document#15]
## 背景、取り組みの理由
- 現状、訳語をどうすれば良いか個別に問い合わせしている状況

## 何をするか

- 対訳表を作成する
  - 完成イメージはこちら。 https://github.com/rust-lang-ja/book-ja/blob/master-ja/TranslationTable.md

## 進め方

- まずスプレッドシートに対訳を書き込む
  - https://docs.google.com/spreadsheets/d/1837fDqN188vnXqLwsgkI3Rr3HsPYTv321C9RYalY9lA/edit#gid=0
  - ※過去の訳などからある程度自動的に書き込めると理想的
- 作業をしながら、原則は言語化する
- 用語の対訳が一通り揃ったら、markdownに変換し、perldoc.jp にページ作成する
  - perldoc.jp に対訳表が作成できたら、その後の更新はスプレッドシートではなく、perldoc.jp の方を更新する

**Comment by argrath** [comment]
http://perldoc.jp/docs/perl/5.10.0/perlglossary.pod

ある時期まではここに見出しの形である程度まとめていました。
(今はリポジトリをgrepしています…)

**Comment by kfly8** [comment]
うおー！！ありがとうございます！！！
これを知っていると翻訳を始めやすそうですね。

perl/5.10.0 を参照する形になっていますが、perl5.36 など追従できると理想的？
perldoc.jp の翻訳マナーのところなど、認知しやすいようにリンクするのも良さそう。

**Comment by kfly8** [comment]
perl5.36のperlglossaryから用語一覧を抜き出し、perldoc.jp の用語集と照らして、対訳表をつくってみました。

https://docs.google.com/spreadsheets/d/1837fDqN188vnXqLwsgkI3Rr3HsPYTv321C9RYalY9lA/edit#gid=0

**Comment by kfly8** [comment]
@argrath  FYI: GitHubの翻訳リポジトリに、対訳表をおくPRを作成しました。
https://github.com/perldoc-jp/module-pod-jp/pull/15

- 新しく翻訳を行う人は、GitHub側の翻訳を利用しそう
- perldoc.jp には、このPRがマージされたら、https://perldoc.jp/manners にリンクを貼れればと思っています。

**Comment by kfly8** [comment]
module-pod-jpの方がマージされたので導線追加のPR投げました！

https://github.com/jpa-perl/perldoc.jp/pull/29

**Comment by kfly8** [comment]
perldoc.jpに導線も掲載されたので、クローズ
